{{- if eq .Values.image.registry "Quay" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-build.name" . }}-registry-creds
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.image_host }}": {
          "auth": "{{ printf "%s:%s" .Values.quay_robot_username .Values.quay_robot_token | b64enc }}"
        }
      }
    }
{{- end }}
