{{- if eq .Values.image_registry "Quay" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-build.name" . }}-registry-creds
  namespace: {{ .Values.namespace }}
  annotations:
    tekton.dev/docker-0: https://{{ .Values.image_host }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.image_host }}": {
          "auth": "{{ printf "%s:%s" .Values.quay_robot_username .Values.quay_robot_token | b64enc }}"
        }
      }
    }
{{- end }}